version: "3.9"
services:
  db:
    image: mysql:5.7
    container_name: goapp_db
    ports:
      - 3306:3306
    command: mysqld --user=root
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goblog
      
  goapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
